# Generated by Django 5.0.1 on 2024-02-09 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_experience', models.CharField(choices=[('perso', 'Personal'), ('pro', 'Professional')], max_length=5)),
                ('programming_languages', models.CharField(max_length=200)),
                ('tools_used', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('starting_date', models.DateTimeField(null=True)),
                ('ending_date', models.DateTimeField(null=True)),
                ('job_title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalInformation',
            fields=[
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
                ('codingame', models.URLField()),
                ('languages', models.CharField(choices=[('FR', 'FR'), ('EN', 'EN')], max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=500)),
                ('detail', models.CharField(max_length=1000)),
                ('accomplishment', models.CharField(max_length=500)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front_page.experiences')),
            ],
        ),
        migrations.CreateModel(
            name='Formations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateTimeField()),
                ('ending_date', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('accomplishment', models.CharField(max_length=500)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front_page.globalinformation')),
            ],
        ),
        migrations.AddField(
            model_name='experiences',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front_page.globalinformation'),
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_text', models.CharField(max_length=500)),
                ('extra_profesionnal_sports', models.CharField(max_length=500)),
                ('extra_profesionnal_activity', models.CharField(max_length=500)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front_page.globalinformation')),
            ],
        ),
    ]
