# Generated by Django 5.0.1 on 2024-02-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_page', '0002_rename_experiences_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalinformation',
            name='phone_number',
        ),
    ]
