# Generated by Django 5.0.1 on 2024-02-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_page', '0003_remove_globalinformation_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='description_text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='extra_profesionnal_activity',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='extra_profesionnal_sports',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='experience',
            name='programming_languages',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='tools_used',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='experiencedetail',
            name='accomplishment',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='experiencedetail',
            name='detail',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='experiencedetail',
            name='goal',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='formation',
            name='accomplishment',
            field=models.TextField(max_length=500),
        ),
    ]
