# Generated by Django 5.0.1 on 2024-02-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_page', '0004_alter_aboutme_description_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='extra_profesionnal_activity',
            field=models.CharField(max_length=100),
        ),
    ]
