# Generated by Django 5.0.1 on 2024-02-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_page', '0005_alter_aboutme_extra_profesionnal_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='ending_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='starting_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='ending_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='formation',
            name='starting_date',
            field=models.DateField(),
        ),
    ]
