# Generated by Django 5.0.1 on 2024-02-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_page', '0006_alter_experience_ending_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='experiencedetail',
            name='accomplishment',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='experiencedetail',
            name='detail',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='experiencedetail',
            name='goal',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='formation',
            name='accomplishment',
            field=models.TextField(max_length=1000),
        ),
    ]
